# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'SpaceSoldierApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceSoldierApp
  pod 'kintone-ios-sdk'
  pod 'CryptoSwift'
  pod 'PromisesSwift', '~> 1.2.7'		
end
